export const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  TOGGLE_ACCOUNT_MODAL_HIDDEN: "TOGGLE_ACCOUNT_MODAL_HIDDEN",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",

  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",

  SIGN_IN_START: "SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",

  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",

  PASSWORD_RESET_START: "PASSWORD_RESET_START",
  PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",
  PASSWORD_RESET_FAILURE: "PASSWORD_RESET_FAILURE",

  FETCH_USER_ORDERS_START: "FETCH_USER_ORDERS_START",
  FETCH_USER_ORDERS_SUCCESS: "FETCH_USER_ORDERS_SUCCESS",
  FETCH_USER_ORDERS_FAILURE: "FETCH_USER_ORDERS_FAILURE",
};

export default UserActionTypes;
