export const RestaurantActionTypes = {
  FETCH_RESTAURANT_MENU_START: "FETCH_RESTAURANT_MENU_START",
  FETCH_RESTAURANT_MENU_SUCCESS: "FETCH_RESTAURANT_MENU_SUCCESS",
  FETCH_RESTAURANT_MENU_FAILURE: "FETCH_RESTAURANT_MENU_FAILURE",
};
