const RESTAURANT_DATA = [
  {
    categoryID: 10,
    categoryName: "Pizza",
    categoryIcon: "",
    products: [
      {
        productID: 51,
        nameRO: "Rossignol",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "575 gr",
        price: 36,
        descriptionRO:
          "Sos de rosii, mozzarella, sunca, ciuperci, salam, aredi gras, masline",
        descriptionENG:
          "Tomato sauce, mozzarella, ham, mushrooms, salami, olives",
      },
      {
        productID: 52,
        nameRO: "Special Snow",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "490 gr",
        price: 37,
        descriptionRO:
          "Sos de rosii, mozzarella, emmentaler, cascaval, prosciutto crudo",
        descriptionENG:
          "Tomato sauce, mozzarella, emmental, cheese, prosciutto crudo",
      },
      {
        productID: 53,
        nameRO: "Quattro Formaggi",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "420 gr",
        price: 35,
        descriptionRO:
          "Sos de rosii, mozzarella, emmentaler, gorgonzola, cascava;",
        descriptionENG:
          "Tomato sauce, mozzarella, emmental, gorgonnzola , cheese",
      },
      {
        productID: 54,
        nameRO: "Margherita",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "380 gr",
        price: 24,
        descriptionRO: "Sos de rosii, mozzarella",
        descriptionENG: "Tomato sauce, mozzarella",
      },
      {
        productID: 55,
        nameRO: "Funghi",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "490 gr",
        price: 38,
        descriptionRO: "Sos de rosii, mozzarella, ciuperci",
        descriptionENG: "Tomato sauce, mozzarella, mushrooms",
      },
      {
        productID: 56,
        nameRO: "Prosciutto",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "490 gr",
        price: 28,
        descriptionRO: "Sos de rosii, mozzarella, sunca",
        descriptionENG: "Tomato sauce, mozzarella, ham",
      },
      {
        productID: 57,
        nameRO: "Prosciutto Funghi",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "490 gr",
        price: 30,
        descriptionRO: "Sos de rosii, mozzarella, sunca, ciuperci",
        descriptionENG: "Tomato sauce, mozzarella, ham, mushrooms",
      },
      {
        productID: 58,
        nameRO: "Romana",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "510 gr",
        price: 31,
        descriptionRO: "Sos de rosii, mozzarella, sunca, salam, ciuperci",
        descriptionENG: "Tomatoe sauce, mozzarella, ham, salami, mushrooms",
      },
      {
        productID: 59,
        nameRO: "Capriciosa",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "510 gr",
        price: 30,
        descriptionRO: "Sos de rosii, mozzarella, ciuperci, anghinare, sunca",
        descriptionENG:
          "Tomatoe sauce, mozzarella, mushrooms, artichoke hearts, ham",
      },
      {
        productID: 60,
        nameRO: "Quattro Stagioni",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "535 gr",
        price: 31,
        descriptionRO: "Sos de rosii, mozzarella, sunca, anghinare, masline",
        descriptionENG:
          "Tomato sauce, mozzarella, ham, artichoke hearts, olives",
      },
      {
        productID: 61,
        nameRO: "Diavolo",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "470 gr",
        price: 28,
        descriptionRO: "Sos de rosii, mozzarella, salam picant",
        descriptionENG: "Tomato sauce, mozzarella, spcied salami",
      },
      {
        productID: 62,
        nameRO: "Al Tonno",
        nameENG: "",
        alergens: "[2, 3, 9]",
        quantity: "490 gr",
        price: 31,
        descriptionRO: "Sos de rosii, mozzarella, ton, ceapa",
        descriptionENG: "Tomato sauce, mozzarella, tuna, onion",
      },
      {
        productID: 63,
        nameRO: "Hawai",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "375 gr",
        price: 27,
        descriptionRO: "Sos de rosii, mozzarella, ananas",
        descriptionENG: "Tomato sauce, mozzarella, pineapple",
      },
      {
        productID: 64,
        nameRO: "Dracula",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "470 gr",
        price: 30,
        descriptionRO:
          "Sos de rosii, mozzarella, bacon, ceapa, usturoi, ardei iute",
        descriptionENG:
          "Tomato sauce, mozzarella, bacon, onion, garlic, chili pepper",
      },
      {
        productID: 65,
        nameRO: "Mexicana",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "480 gr",
        price: 29,
        descriptionRO: "Sos de rosii, mozzarella, carnati, ardei iute",
        descriptionENG: "Tomato sauce, mozzarella, sausages, chili pepper",
      },
      {
        productID: 66,
        nameRO: "Vegetariana",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "470 gr",
        price: 27,
        descriptionRO:
          "Sos de rosii, mozzarella, ciuperci, porumb, ardei gras, rosi, masline",
        descriptionENG:
          "Tomato sauce, mozzarella, mushrroms, corn, bell pepper, tomatoes, olives",
      },
      {
        productID: 67,
        nameRO: "Quattro Carni",
        nameENG: "",
        alergens: "[2, 9]",
        quantity: "470 gr",
        price: 34,
        descriptionRO: "Sos de rosii, mozzarella, sunca, bacon, carnati, salam",
        descriptionENG:
          "Tomato sauce, mozzarella, ham, bacon, sausages, salami",
      },
      {
        productID: 68,
        nameRO: "Focaccia",
        nameENG: "",
        alergens: "[9]",
        quantity: "420 gr",
        price: 13,
        descriptionRO: "",
        descriptionENG: "",
      },
      {
        productID: 69,
        nameRO: "Sos dulce / Sos picant",
        nameENG: "Sweet sauce / Spicy sauce",
        quantity: "50 gr",
        price: 3,
        descriptionRO: "",
        descriptionENG: "",
      },
    ],
  },
];

export default RESTAURANT_DATA;
